/* 
Global Solution - VOID 
Guilherme Macedo
Henrique Martins
Pedro Henrique
*/

-- Configuração de Ambiente
SET VERIFY OFF;
SET SERVEROUTPUT ON;
DROP TABLE TELEMETRIA_RAW_JSON CASCADE CONSTRAINTS;
DROP TABLE LOG_AUDITORIA_SESSAO CASCADE CONSTRAINTS;
DROP TABLE ALERTA_CRITICO CASCADE CONSTRAINTS;
DROP TABLE LEITURA_FADIGA CASCADE CONSTRAINTS;
DROP TABLE TB_VOID_SESSAO_REABILITACAO CASCADE CONSTRAINTS;
DROP TABLE SENSOR_WEARABLE CASCADE CONSTRAINTS;
DROP TABLE PROTOCOLO_ESPACIAL CASCADE CONSTRAINTS;
DROP TABLE TB_VOID_FISIOTERAPEUTA CASCADE CONSTRAINTS;
DROP TABLE TB_VOID_PACIENTE CASCADE CONSTRAINTS;
DROP TABLE TB_VOID_USUARIO CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_TB_USUARIO;
DROP SEQUENCE SEQ_ALERTA;

----------------------------
--  DDL - CRIAÇÃO DE TABELAS 
----------------------------

-- Tabela de Usuários
CREATE TABLE TB_VOID_USUARIO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(11) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    TIPO_USUARIO CHAR(1) NOT NULL
);

-- Sequência para geração automática do ID de usuários 
CREATE SEQUENCE SEQ_TB_USUARIO START WITH 11 INCREMENT BY 1;

-- Dados medicos do paciente
CREATE TABLE TB_VOID_PACIENTE (
    ID_USUARIO NUMBER PRIMARY KEY,
    LIMITE_ESFORCO_CRITICO NUMBER(5,2) NOT NULL,
    CONSTRAINT FK_PAC_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_VOID_USUARIO(ID)
);

-- Identificaçao do fisioterapeuta
CREATE TABLE TB_VOID_FISIOTERAPEUTA (
    ID_USUARIO NUMBER PRIMARY KEY,
    REGISTRO_PROFISSIONAL VARCHAR2(20) UNIQUE NOT NULL,
    CONSTRAINT FK_FIS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_VOID_USUARIO(ID)
);

-- Tabela para carga espaciais
CREATE TABLE PROTOCOLO_ESPACIAL (
    ID_PROTOCOLO NUMBER PRIMARY KEY,
    NOME_PROTOCOLO VARCHAR2(100) NOT NULL,
    LIMITE_FADIGA_MAXIMA NUMBER(5,2) NOT NULL
);

-- Controle dos dispositivos esp32 cadastrados
CREATE TABLE SENSOR_WEARABLE (
    ID_SENSOR NUMBER PRIMARY KEY,
    MAC_ADDRESS VARCHAR2(17) UNIQUE NOT NULL,
    STATUS VARCHAR2(10) DEFAULT 'ATIVO'
);

-- Controle de agendamento e execucao dos treinos
CREATE TABLE TB_VOID_SESSAO_REABILITACAO (
    PACIENTE_ID NUMBER NOT NULL,
    DATA_SESSAO DATE NOT NULL,
    DESGASTE_ACUMULADO NUMBER(5,2),
    ALERTA_FADIGA_CRITICA NUMBER(1) DEFAULT 0,
    ID_FISIO NUMBER NOT NULL,
    ID_PROTOCOLO NUMBER NOT NULL,
    STATUS_SESSAO VARCHAR2(20) DEFAULT 'ANDAMENTO',
    CONSTRAINT PK_SESSAO PRIMARY KEY (PACIENTE_ID, DATA_SESSAO),
    CONSTRAINT FK_SESSAO_PAC FOREIGN KEY (PACIENTE_ID) REFERENCES TB_VOID_PACIENTE(ID_USUARIO),
    CONSTRAINT FK_SESSAO_FIS FOREIGN KEY (ID_FISIO) REFERENCES TB_VOID_FISIOTERAPEUTA(ID_USUARIO),
    CONSTRAINT FK_SESSAO_PROT FOREIGN KEY (ID_PROTOCOLO) REFERENCES PROTOCOLO_ESPACIAL(ID_PROTOCOLO)
);

-- Tabela de telemetria 
CREATE TABLE LEITURA_FADIGA (
    PACIENTE_ID NUMBER NOT NULL,
    DATA_SESSAO DATE NOT NULL,
    SEGUNDO_LEITURA NUMBER NOT NULL,
    ID_SENSOR NUMBER NOT NULL,
    PERCENTUAL_DESGASTE NUMBER(5,2) NOT NULL,
    CONSTRAINT PK_LEITURA PRIMARY KEY (PACIENTE_ID, DATA_SESSAO, SEGUNDO_LEITURA),
    CONSTRAINT FK_LEIT_SESSAO FOREIGN KEY (PACIENTE_ID, DATA_SESSAO) REFERENCES TB_VOID_SESSAO_REABILITACAO(PACIENTE_ID, DATA_SESSAO) ON DELETE CASCADE,
    CONSTRAINT FK_LEIT_SENSOR FOREIGN KEY (ID_SENSOR) REFERENCES SENSOR_WEARABLE(ID_SENSOR)
);

-- Historico de quebras de limite de segurança
CREATE TABLE ALERTA_CRITICO (
    ID_ALERTA NUMBER PRIMARY KEY,
    PACIENTE_ID NUMBER NOT NULL,
    DATA_SESSAO DATE NOT NULL,
    TIMESTAMP_ALERTA TIMESTAMP NOT NULL,
    NIVEL_ATINGIDO NUMBER(5,2),
    CONSTRAINT FK_ALERTA_SESSAO FOREIGN KEY (PACIENTE_ID, DATA_SESSAO) REFERENCES TB_VOID_SESSAO_REABILITACAO(PACIENTE_ID, DATA_SESSAO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_ALERTA START WITH 1 INCREMENT BY 1;

-- Auditoria de atualizacoes na sessao
CREATE TABLE LOG_AUDITORIA_SESSAO (
    DATA_HORA TIMESTAMP,
    ACAO VARCHAR2(20),
    PACIENTE_ID NUMBER,
    DATA_SESSAO DATE,
    STATUS_ANTIGO VARCHAR2(20)
);

-- nosql integrada usando coluna como json
CREATE TABLE TELEMETRIA_RAW_JSON (
    ID_LOG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PACIENTE_ID NUMBER NOT NULL,
    DATA_SESSAO DATE NOT NULL,
    DADOS_JSON CLOB,
    CONSTRAINT CK_DADOS_JSON CHECK (DADOS_JSON IS JSON)
);

------------------------
--  DML - CARGA DE DADOS 
------------------------

-- TB_VOID_USUARIO 5 Pacientes + 5 Fisioterapeutas
INSERT INTO TB_VOID_USUARIO VALUES (1, 'Carlos Silva', '11111111111', 'carlos@void.com', 'P');
INSERT INTO TB_VOID_USUARIO VALUES (2, 'Ana Souza', '22222222222', 'ana@void.com', 'P');
INSERT INTO TB_VOID_USUARIO VALUES (3, 'Bruno Mendes', '33333333333', 'bruno@void.com', 'P');
INSERT INTO TB_VOID_USUARIO VALUES (4, 'Fernanda Lima', '44444444444', 'fernanda@void.com', 'P');
INSERT INTO TB_VOID_USUARIO VALUES (5, 'Juliana Castro', '55555555555', 'juliana@void.com', 'P');
INSERT INTO TB_VOID_USUARIO VALUES (6, 'Dr. Roberto Alves', '66666666666', 'roberto@void.com', 'F');
INSERT INTO TB_VOID_USUARIO VALUES (7, 'Dra. Marcia Nunes', '77777777777', 'marcia@void.com', 'F');
INSERT INTO TB_VOID_USUARIO VALUES (8, 'Dr. Pedro Costa', '88888888888', 'pedro@void.com', 'F');
INSERT INTO TB_VOID_USUARIO VALUES (9, 'Dra. Camila Rocha', '99999999999', 'camila@void.com', 'F');
INSERT INTO TB_VOID_USUARIO VALUES (10, 'Dr. Tiago Santos', '00000000000', 'tiago@void.com', 'F');

-- TB_VOID_PACIENTE
INSERT INTO TB_VOID_PACIENTE VALUES (1, 80.5);
INSERT INTO TB_VOID_PACIENTE VALUES (2, 75.0);
INSERT INTO TB_VOID_PACIENTE VALUES (3, 85.0);
INSERT INTO TB_VOID_PACIENTE VALUES (4, 70.5);
INSERT INTO TB_VOID_PACIENTE VALUES (5, 90.0);

-- TB_VOID_FISIOTERAPEUTA
INSERT INTO TB_VOID_FISIOTERAPEUTA VALUES (6, 'CREFITO-1001');
INSERT INTO TB_VOID_FISIOTERAPEUTA VALUES (7, 'CREFITO-1002');
INSERT INTO TB_VOID_FISIOTERAPEUTA VALUES (8, 'CREFITO-1003');
INSERT INTO TB_VOID_FISIOTERAPEUTA VALUES (9, 'CREFITO-1004');
INSERT INTO TB_VOID_FISIOTERAPEUTA VALUES (10, 'CREFITO-1005');

-- PROTOCOLO_ESPACIAL
INSERT INTO PROTOCOLO_ESPACIAL VALUES (1, 'Protocolo ISS Padrão', 80.00);
INSERT INTO PROTOCOLO_ESPACIAL VALUES (2, 'Recuperação Leve', 60.00);
INSERT INTO PROTOCOLO_ESPACIAL VALUES (3, 'Cardio Moderado', 75.00);
INSERT INTO PROTOCOLO_ESPACIAL VALUES (4, 'Resistência Muscular', 85.00);
INSERT INTO PROTOCOLO_ESPACIAL VALUES (5, 'Mobilidade Articular', 50.00);
INSERT INTO PROTOCOLO_ESPACIAL VALUES (6, 'Força Progressiva', 88.00);
INSERT INTO PROTOCOLO_ESPACIAL VALUES (7, 'Micro-Gravidade Sim.', 40.00);
INSERT INTO PROTOCOLO_ESPACIAL VALUES (8, 'Fadiga Controlada', 90.00);
INSERT INTO PROTOCOLO_ESPACIAL VALUES (9, 'Reabilitação Severa', 55.00);
INSERT INTO PROTOCOLO_ESPACIAL VALUES (10, 'Teste de Limite Máximo', 95.00);

-- SENSOR_WEARABLE
INSERT INTO SENSOR_WEARABLE VALUES (1, '00:1B:44:11:3A:B1', 'ATIVO');
INSERT INTO SENSOR_WEARABLE VALUES (2, '00:1B:44:11:3A:B2', 'ATIVO');
INSERT INTO SENSOR_WEARABLE VALUES (3, '00:1B:44:11:3A:B3', 'MANUTENCAO');
INSERT INTO SENSOR_WEARABLE VALUES (4, '00:1B:44:11:3A:B4', 'ATIVO');
INSERT INTO SENSOR_WEARABLE VALUES (5, '00:1B:44:11:3A:B5', 'INATIVO');
INSERT INTO SENSOR_WEARABLE VALUES (6, '00:1B:44:11:3A:B6', 'ATIVO');
INSERT INTO SENSOR_WEARABLE VALUES (7, '00:1B:44:11:3A:B7', 'ATIVO');
INSERT INTO SENSOR_WEARABLE VALUES (8, '00:1B:44:11:3A:B8', 'CALIBRACAO');
INSERT INTO SENSOR_WEARABLE VALUES (9, '00:1B:44:11:3A:B9', 'ATIVO');
INSERT INTO SENSOR_WEARABLE VALUES (10, '00:1B:44:11:3A:C0', 'ATIVO');

-- TB_VOID_SESSAO_REABILITACAO
INSERT INTO TB_VOID_SESSAO_REABILITACAO VALUES (1, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 45.2, 0, 6, 1, 'CONCLUIDA');
INSERT INTO TB_VOID_SESSAO_REABILITACAO VALUES (1, TO_DATE('2026-05-02', 'YYYY-MM-DD'), 60.1, 0, 6, 1, 'CONCLUIDA');
INSERT INTO TB_VOID_SESSAO_REABILITACAO VALUES (2, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 78.5, 1, 7, 3, 'CANCELADA');
INSERT INTO TB_VOID_SESSAO_REABILITACAO VALUES (2, TO_DATE('2026-05-03', 'YYYY-MM-DD'), 50.0, 0, 7, 2, 'CONCLUIDA');
INSERT INTO TB_VOID_SESSAO_REABILITACAO VALUES (3, TO_DATE('2026-05-05', 'YYYY-MM-DD'), 82.0, 1, 8, 4, 'CONCLUIDA');
INSERT INTO TB_VOID_SESSAO_REABILITACAO VALUES (3, TO_DATE('2026-05-07', 'YYYY-MM-DD'), 30.0, 0, 8, 5, 'ANDAMENTO');
INSERT INTO TB_VOID_SESSAO_REABILITACAO VALUES (4, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 88.5, 1, 9, 8, 'CONCLUIDA');
INSERT INTO TB_VOID_SESSAO_REABILITACAO VALUES (4, TO_DATE('2026-05-04', 'YYYY-MM-DD'), 0.0, 0, 9, 8, 'AGENDADA');
INSERT INTO TB_VOID_SESSAO_REABILITACAO VALUES (5, TO_DATE('2026-05-10', 'YYYY-MM-DD'), 40.5, 0, 10, 7, 'ANDAMENTO');
INSERT INTO TB_VOID_SESSAO_REABILITACAO VALUES (5, TO_DATE('2026-05-12', 'YYYY-MM-DD'), 0.0, 0, 10, 7, 'AGENDADA');

-- LEITURA_FADIGA
INSERT INTO LEITURA_FADIGA VALUES (1, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 1, 1, 10.5);
INSERT INTO LEITURA_FADIGA VALUES (1, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 2, 1, 15.2);
INSERT INTO LEITURA_FADIGA VALUES (1, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 3, 1, 20.8);
INSERT INTO LEITURA_FADIGA VALUES (2, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 1, 2, 70.0);
INSERT INTO LEITURA_FADIGA VALUES (2, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 2, 2, 78.5);
INSERT INTO LEITURA_FADIGA VALUES (3, TO_DATE('2026-05-05', 'YYYY-MM-DD'), 1, 4, 80.0);
INSERT INTO LEITURA_FADIGA VALUES (3, TO_DATE('2026-05-05', 'YYYY-MM-DD'), 2, 4, 82.0);
INSERT INTO LEITURA_FADIGA VALUES (4, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 1, 6, 85.0);
INSERT INTO LEITURA_FADIGA VALUES (4, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 2, 6, 88.5);
INSERT INTO LEITURA_FADIGA VALUES (5, TO_DATE('2026-05-10', 'YYYY-MM-DD'), 1, 7, 40.5);

-- ALERTA_CRITICO
INSERT INTO ALERTA_CRITICO VALUES (SEQ_ALERTA.NEXTVAL, 2, TO_DATE('2026-05-01', 'YYYY-MM-DD'), SYSTIMESTAMP, 78.5);
INSERT INTO ALERTA_CRITICO VALUES (SEQ_ALERTA.NEXTVAL, 3, TO_DATE('2026-05-05', 'YYYY-MM-DD'), SYSTIMESTAMP, 81.0);
INSERT INTO ALERTA_CRITICO VALUES (SEQ_ALERTA.NEXTVAL, 3, TO_DATE('2026-05-05', 'YYYY-MM-DD'), SYSTIMESTAMP, 82.0);
INSERT INTO ALERTA_CRITICO VALUES (SEQ_ALERTA.NEXTVAL, 4, TO_DATE('2026-05-01', 'YYYY-MM-DD'), SYSTIMESTAMP, 86.0);
INSERT INTO ALERTA_CRITICO VALUES (SEQ_ALERTA.NEXTVAL, 4, TO_DATE('2026-05-01', 'YYYY-MM-DD'), SYSTIMESTAMP, 87.5);
INSERT INTO ALERTA_CRITICO VALUES (SEQ_ALERTA.NEXTVAL, 4, TO_DATE('2026-05-01', 'YYYY-MM-DD'), SYSTIMESTAMP, 88.5);
INSERT INTO ALERTA_CRITICO VALUES (SEQ_ALERTA.NEXTVAL, 2, TO_DATE('2026-05-01', 'YYYY-MM-DD'), SYSTIMESTAMP, 76.0);
INSERT INTO ALERTA_CRITICO VALUES (SEQ_ALERTA.NEXTVAL, 1, TO_DATE('2026-05-02', 'YYYY-MM-DD'), SYSTIMESTAMP, 60.1);
INSERT INTO ALERTA_CRITICO VALUES (SEQ_ALERTA.NEXTVAL, 1, TO_DATE('2026-05-02', 'YYYY-MM-DD'), SYSTIMESTAMP, 58.0);
INSERT INTO ALERTA_CRITICO VALUES (SEQ_ALERTA.NEXTVAL, 5, TO_DATE('2026-05-10', 'YYYY-MM-DD'), SYSTIMESTAMP, 40.5);

-- LOG_AUDITORIA_SESSAO
INSERT INTO LOG_AUDITORIA_SESSAO VALUES (SYSTIMESTAMP, 'UPDATE', 1, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 'ANDAMENTO');
INSERT INTO LOG_AUDITORIA_SESSAO VALUES (SYSTIMESTAMP, 'UPDATE', 1, TO_DATE('2026-05-02', 'YYYY-MM-DD'), 'ANDAMENTO');
INSERT INTO LOG_AUDITORIA_SESSAO VALUES (SYSTIMESTAMP, 'CANCEL', 2, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 'ANDAMENTO');
INSERT INTO LOG_AUDITORIA_SESSAO VALUES (SYSTIMESTAMP, 'UPDATE', 2, TO_DATE('2026-05-03', 'YYYY-MM-DD'), 'AGENDADA');
INSERT INTO LOG_AUDITORIA_SESSAO VALUES (SYSTIMESTAMP, 'UPDATE', 3, TO_DATE('2026-05-05', 'YYYY-MM-DD'), 'ANDAMENTO');
INSERT INTO LOG_AUDITORIA_SESSAO VALUES (SYSTIMESTAMP, 'CREATE', 3, TO_DATE('2026-05-07', 'YYYY-MM-DD'), NULL);
INSERT INTO LOG_AUDITORIA_SESSAO VALUES (SYSTIMESTAMP, 'UPDATE', 4, TO_DATE('2026-05-01', 'YYYY-MM-DD'), 'ANDAMENTO');
INSERT INTO LOG_AUDITORIA_SESSAO VALUES (SYSTIMESTAMP, 'CREATE', 4, TO_DATE('2026-05-04', 'YYYY-MM-DD'), NULL);
INSERT INTO LOG_AUDITORIA_SESSAO VALUES (SYSTIMESTAMP, 'UPDATE', 5, TO_DATE('2026-05-10', 'YYYY-MM-DD'), 'AGENDADA');
INSERT INTO LOG_AUDITORIA_SESSAO VALUES (SYSTIMESTAMP, 'CREATE', 5, TO_DATE('2026-05-12', 'YYYY-MM-DD'), NULL);

-- TELEMETRIA_RAW_JSON
INSERT INTO TELEMETRIA_RAW_JSON (PACIENTE_ID, DATA_SESSAO, DADOS_JSON) VALUES (1, TO_DATE('2026-05-01', 'YYYY-MM-DD'), '{"sensor": "ESP32_01", "temperatura": 36.5, "bateria": 88}');
INSERT INTO TELEMETRIA_RAW_JSON (PACIENTE_ID, DATA_SESSAO, DADOS_JSON) VALUES (1, TO_DATE('2026-05-02', 'YYYY-MM-DD'), '{"sensor": "ESP32_01", "temperatura": 36.8, "bateria": 85}');
INSERT INTO TELEMETRIA_RAW_JSON (PACIENTE_ID, DATA_SESSAO, DADOS_JSON) VALUES (2, TO_DATE('2026-05-01', 'YYYY-MM-DD'), '{"sensor": "ESP32_02", "temperatura": 37.1, "bateria": 90}');
INSERT INTO TELEMETRIA_RAW_JSON (PACIENTE_ID, DATA_SESSAO, DADOS_JSON) VALUES (2, TO_DATE('2026-05-03', 'YYYY-MM-DD'), '{"sensor": "ESP32_02", "temperatura": 36.6, "bateria": 75}');
INSERT INTO TELEMETRIA_RAW_JSON (PACIENTE_ID, DATA_SESSAO, DADOS_JSON) VALUES (3, TO_DATE('2026-05-05', 'YYYY-MM-DD'), '{"sensor": "ESP32_04", "temperatura": 37.5, "bateria": 60}');
INSERT INTO TELEMETRIA_RAW_JSON (PACIENTE_ID, DATA_SESSAO, DADOS_JSON) VALUES (3, TO_DATE('2026-05-07', 'YYYY-MM-DD'), '{"sensor": "ESP32_04", "temperatura": 36.5, "bateria": 100}');
INSERT INTO TELEMETRIA_RAW_JSON (PACIENTE_ID, DATA_SESSAO, DADOS_JSON) VALUES (4, TO_DATE('2026-05-01', 'YYYY-MM-DD'), '{"sensor": "ESP32_06", "temperatura": 38.0, "bateria": 45}');
INSERT INTO TELEMETRIA_RAW_JSON (PACIENTE_ID, DATA_SESSAO, DADOS_JSON) VALUES (4, TO_DATE('2026-05-04', 'YYYY-MM-DD'), '{"sensor": "ESP32_06", "temperatura": 36.2, "bateria": 99}');
INSERT INTO TELEMETRIA_RAW_JSON (PACIENTE_ID, DATA_SESSAO, DADOS_JSON) VALUES (5, TO_DATE('2026-05-10', 'YYYY-MM-DD'), '{"sensor": "ESP32_07", "temperatura": 36.9, "bateria": 82}');
INSERT INTO TELEMETRIA_RAW_JSON (PACIENTE_ID, DATA_SESSAO, DADOS_JSON) VALUES (5, TO_DATE('2026-05-12', 'YYYY-MM-DD'), '{"sensor": "ESP32_07", "temperatura": 36.8, "bateria": 100}');

--------------------
--  BLOCOS ANÔNIMOS 
--------------------

-- Loop FOR e INSERT com variável
DECLARE
    v_desgaste NUMBER;
    e_desgaste_invalido EXCEPTION;
BEGIN
    FOR i IN 1..85 LOOP
        v_desgaste := 10 + (i * 0.8); 
        
        -- desgaste não pode passar de 100%
        IF v_desgaste > 100 THEN 
            RAISE e_desgaste_invalido; 
        END IF;
        
        INSERT INTO LEITURA_FADIGA (PACIENTE_ID, DATA_SESSAO, SEGUNDO_LEITURA, ID_SENSOR, PERCENTUAL_DESGASTE)
        VALUES (1, TO_DATE('2026-05-01', 'YYYY-MM-DD'), i + 3, 1, v_desgaste);
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN e_desgaste_invalido THEN 
        DBMS_OUTPUT.PUT_LINE('Erro de Regra de Negócio: Percentual de desgaste excedeu 100%.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro inesperado durante a inserção: ' || SQLERRM);
END;
/

-- Cursor Explícito, LOOP e Condicional
DECLARE
    CURSOR c_leituras IS 
        SELECT SEGUNDO_LEITURA, PERCENTUAL_DESGASTE 
        FROM LEITURA_FADIGA 
        WHERE PACIENTE_ID = 2;
        
    v_segundo LEITURA_FADIGA.SEGUNDO_LEITURA%TYPE;
    v_perc LEITURA_FADIGA.PERCENTUAL_DESGASTE%TYPE;
BEGIN
    OPEN c_leituras;
    LOOP
        FETCH c_leituras INTO v_segundo, v_perc;
        EXIT WHEN c_leituras%NOTFOUND;
        
        IF v_perc > 80.00 THEN
            DBMS_OUTPUT.PUT_LINE('CRÍTICO: Desgaste altíssimo no segundo ' || v_segundo || ' (' || v_perc || '%)');
        ELSIF v_perc > 70.00 THEN
            DBMS_OUTPUT.PUT_LINE('Alerta: Desgaste alto no segundo ' || v_segundo || ' (' || v_perc || '%)');
        ELSE
            DBMS_OUTPUT.PUT_LINE('Desgaste normal no segundo ' || v_segundo);
        END IF;
    END LOOP;
    CLOSE c_leituras;
EXCEPTION
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('Erro ao processar leituras de fadiga: ' || SQLERRM);
END;
/

-- Cursor Explícito WHILE LOOP
DECLARE
    CURSOR c_sensores IS 
        SELECT ID_SENSOR, STATUS 
        FROM SENSOR_WEARABLE;
        
    v_id SENSOR_WEARABLE.ID_SENSOR%TYPE;
    v_status SENSOR_WEARABLE.STATUS%TYPE;
BEGIN
    OPEN c_sensores;
    FETCH c_sensores INTO v_id, v_status;
    
    WHILE c_sensores%FOUND LOOP
        IF v_status = 'ATIVO' THEN
            DBMS_OUTPUT.PUT_LINE('Sensor ' || v_id || ' operante e enviando telemetria.');
        ELSE
            DBMS_OUTPUT.PUT_LINE('Sensor ' || v_id || ' inativo ou aguardando manutenção.');
        END IF;
        FETCH c_sensores INTO v_id, v_status;
    END LOOP;
    
    CLOSE c_sensores;
EXCEPTION
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('Erro na varredura de sensores: ' || SQLERRM);
END;
/
 
-- Cursor Explícito (DELETE)
DECLARE
    CURSOR c_sessoes_canceladas IS 
        SELECT PACIENTE_ID, DATA_SESSAO 
        FROM TB_VOID_SESSAO_REABILITACAO 
        WHERE STATUS_SESSAO = 'CANCELADA';
        
    v_paciente TB_VOID_SESSAO_REABILITACAO.PACIENTE_ID%TYPE;
    v_data TB_VOID_SESSAO_REABILITACAO.DATA_SESSAO%TYPE;
    e_sem_dados EXCEPTION;
BEGIN
    OPEN c_sessoes_canceladas;
    LOOP
        FETCH c_sessoes_canceladas INTO v_paciente, v_data;
        EXIT WHEN c_sessoes_canceladas%NOTFOUND;
        
        DELETE FROM TB_VOID_SESSAO_REABILITACAO 
        WHERE PACIENTE_ID = v_paciente AND DATA_SESSAO = v_data;
    END LOOP;
    
    IF c_sessoes_canceladas%ROWCOUNT = 0 THEN
        RAISE e_sem_dados;
    END IF;
    
    CLOSE c_sessoes_canceladas;
    COMMIT;
EXCEPTION
    WHEN e_sem_dados THEN 
        DBMS_OUTPUT.PUT_LINE('Limpeza: Nenhuma sessão cancelada encontrada para exclusão.');
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('Erro ao excluir sessões: ' || SQLERRM);
END;
/

-- Cursor Explícito FOR UPDATE e Condicional
DECLARE
    CURSOR c_equip IS 
        SELECT ID_SENSOR 
        FROM SENSOR_WEARABLE 
        FOR UPDATE;
        
    v_id_sensor SENSOR_WEARABLE.ID_SENSOR%TYPE;
BEGIN
    OPEN c_equip;
    LOOP
        FETCH c_equip INTO v_id_sensor;
        EXIT WHEN c_equip%NOTFOUND;
        
        IF v_id_sensor = 1 THEN
            UPDATE SENSOR_WEARABLE 
            SET STATUS = 'CALIBRACAO' 
            WHERE CURRENT OF c_equip;
        END IF;
    END LOOP;
    CLOSE c_equip;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('Erro na atualização de calibração de sensores: ' || SQLERRM);
END;
/

-- SELECT com condicionais e tratamento de exceções 
DECLARE
    v_tipo_usuario TB_VOID_USUARIO.TIPO_USUARIO%TYPE;
BEGIN
    SELECT TIPO_USUARIO INTO v_tipo_usuario 
    FROM TB_VOID_USUARIO 
    WHERE ID = 1;
    
    IF v_tipo_usuario = 'P' THEN
        DBMS_OUTPUT.PUT_LINE('Usuário validado como Paciente apto para protocolo espacial.');
    ELSIF v_tipo_usuario = 'F' THEN
        DBMS_OUTPUT.PUT_LINE('Usuário validado como Fisioterapeuta responsável.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Tipo de usuário desconhecido no sistema.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Erro: Usuário não encontrado no banco de dados.');
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('Erro de Integridade: Mais de um usuário retornado para o mesmo ID.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro inesperado na validação de usuário: ' || SQLERRM);
END;
/

----------
--  PL/SQL
----------

-- Para automatizar a auditoria de mudança de status da sessão
CREATE OR REPLACE TRIGGER TRG_AUDITORIA_SESSAO
AFTER UPDATE OF STATUS_SESSAO ON TB_VOID_SESSAO_REABILITACAO
FOR EACH ROW
BEGIN
    INSERT INTO LOG_AUDITORIA_SESSAO (DATA_HORA, ACAO, PACIENTE_ID, DATA_SESSAO, STATUS_ANTIGO)
    VALUES (SYSTIMESTAMP, 'UPDATE_STATUS', :NEW.PACIENTE_ID, :NEW.DATA_SESSAO, :OLD.STATUS_SESSAO);
END;
/

-- Agrupando procedure e function
CREATE OR REPLACE PACKAGE PKG_VOID_SYSTEM AS
    PROCEDURE PR_CANCELA_SESSAO(p_paciente_id NUMBER, p_data DATE);
    FUNCTION FN_TOTAL_ALERTAS(p_paciente_id NUMBER) RETURN NUMBER;
END PKG_VOID_SYSTEM;
/

-- Criação do Package Body
CREATE OR REPLACE PACKAGE BODY PKG_VOID_SYSTEM AS

    -- Para cancelar sessões de forma segura
    PROCEDURE PR_CANCELA_SESSAO(p_paciente_id NUMBER, p_data DATE) IS
    BEGIN
        UPDATE TB_VOID_SESSAO_REABILITACAO 
        SET STATUS_SESSAO = 'CANCELADA' 
        WHERE PACIENTE_ID = p_paciente_id AND DATA_SESSAO = p_data;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN 
            DBMS_OUTPUT.PUT_LINE('Erro ao executar procedure de cancelamento: ' || SQLERRM);
            ROLLBACK;
    END PR_CANCELA_SESSAO;

    -- Contabilizar o número de alertas críticos de um paciente
    FUNCTION FN_TOTAL_ALERTAS(p_paciente_id NUMBER) RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_total 
        FROM ALERTA_CRITICO 
        WHERE PACIENTE_ID = p_paciente_id;
        
        RETURN v_total;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN 
            RETURN 0;
        WHEN OTHERS THEN
            RETURN -1;
    END FN_TOTAL_ALERTAS;

END PKG_VOID_SYSTEM;
/

-------------------------
--  RELATÓRIOS GERENCIAIS 
-------------------------

-- Relatório de sessões de reabilitação
SELECT 
    s.DATA_SESSAO, 
    p.NOME AS PACIENTE, 
    f.NOME AS FISIOTERAPEUTA, 
    pr.NOME_PROTOCOLO, 
    s.STATUS_SESSAO
FROM TB_VOID_SESSAO_REABILITACAO s
INNER JOIN TB_VOID_USUARIO p ON s.PACIENTE_ID = p.ID
INNER JOIN TB_VOID_USUARIO f ON s.ID_FISIO = f.ID
INNER JOIN PROTOCOLO_ESPACIAL pr ON s.ID_PROTOCOLO = pr.ID_PROTOCOLO
ORDER BY s.DATA_SESSAO DESC;

-- Relatório de alertas críticos vs limite de segurança do paciente
SELECT 
    a.TIMESTAMP_ALERTA, 
    u.NOME AS PACIENTE, 
    a.NIVEL_ATINGIDO AS DESGASTE_REGISTRADO, 
    p.LIMITE_ESFORCO_CRITICO AS LIMITE_PERMITIDO
FROM ALERTA_CRITICO a
INNER JOIN TB_VOID_PACIENTE p ON a.PACIENTE_ID = p.ID_USUARIO
INNER JOIN TB_VOID_USUARIO u ON p.ID_USUARIO = u.ID
ORDER BY a.TIMESTAMP_ALERTA DESC;

-- Relatório de desgaste excessivo por equipamento wearable
SELECT 
    l.DATA_SESSAO, 
    l.SEGUNDO_LEITURA, 
    l.PERCENTUAL_DESGASTE, 
    sw.MAC_ADDRESS, 
    sw.STATUS AS STATUS_WEARABLE
FROM LEITURA_FADIGA l
INNER JOIN SENSOR_WEARABLE sw ON l.ID_SENSOR = sw.ID_SENSOR
WHERE l.PERCENTUAL_DESGASTE > 80
ORDER BY l.PERCENTUAL_DESGASTE DESC;

-- Relatório de vínculo: Pacientes e os Fisioterapeutas que os atenderam
SELECT DISTINCT 
    u_pac.NOME AS NOME_PACIENTE, 
    u_fis.NOME AS NOME_FISIOTERAPEUTA, 
    fis.REGISTRO_PROFISSIONAL AS CREFITO
FROM TB_VOID_SESSAO_REABILITACAO s
INNER JOIN TB_VOID_USUARIO u_pac ON s.PACIENTE_ID = u_pac.ID
INNER JOIN TB_VOID_FISIOTERAPEUTA fis ON s.ID_FISIO = fis.ID_USUARIO
INNER JOIN TB_VOID_USUARIO u_fis ON fis.ID_USUARIO = u_fis.ID;

-- Relatório de Telemetria JSON por sessão
SELECT 
    t.DATA_SESSAO, 
    u.NOME AS PACIENTE, 
    t.DADOS_JSON AS PAYLOAD_BRUTO
FROM TELEMETRIA_RAW_JSON t
INNER JOIN TB_VOID_USUARIO u ON t.PACIENTE_ID = u.ID
ORDER BY t.DATA_SESSAO ASC;